# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/RCA/algo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/RCA/algo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/RCA/algo/CMakeFiles /Volumes/RCA/algo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/RCA/algo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess_wizard

# Build rule for target.
chess_wizard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chess_wizard
.PHONY : chess_wizard

# fast build rule for target.
chess_wizard/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/build
.PHONY : chess_wizard/fast

#=============================================================================
# Target rules for targets named libchesswizard

# Build rule for target.
libchesswizard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libchesswizard
.PHONY : libchesswizard

# fast build rule for target.
libchesswizard/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/build
.PHONY : libchesswizard/fast

#=============================================================================
# Target rules for targets named libchesswizard_shared

# Build rule for target.
libchesswizard_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libchesswizard_shared
.PHONY : libchesswizard_shared

# fast build rule for target.
libchesswizard_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/build
.PHONY : libchesswizard_shared/fast

src/attack.o: src/attack.cpp.o
.PHONY : src/attack.o

# target to build an object file
src/attack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/attack.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/attack.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/attack.cpp.o
.PHONY : src/attack.cpp.o

src/attack.i: src/attack.cpp.i
.PHONY : src/attack.i

# target to preprocess a source file
src/attack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/attack.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/attack.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/attack.cpp.i
.PHONY : src/attack.cpp.i

src/attack.s: src/attack.cpp.s
.PHONY : src/attack.s

# target to generate assembly for a file
src/attack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/attack.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/attack.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/attack.cpp.s
.PHONY : src/attack.cpp.s

src/bitboard.o: src/bitboard.cpp.o
.PHONY : src/bitboard.o

# target to build an object file
src/bitboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/bitboard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/bitboard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/bitboard.cpp.o
.PHONY : src/bitboard.cpp.o

src/bitboard.i: src/bitboard.cpp.i
.PHONY : src/bitboard.i

# target to preprocess a source file
src/bitboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/bitboard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/bitboard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/bitboard.cpp.i
.PHONY : src/bitboard.cpp.i

src/bitboard.s: src/bitboard.cpp.s
.PHONY : src/bitboard.s

# target to generate assembly for a file
src/bitboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/bitboard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/bitboard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/bitboard.cpp.s
.PHONY : src/bitboard.cpp.s

src/book.o: src/book.cpp.o
.PHONY : src/book.o

# target to build an object file
src/book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/book.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/book.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/book.cpp.o
.PHONY : src/book.cpp.o

src/book.i: src/book.cpp.i
.PHONY : src/book.i

# target to preprocess a source file
src/book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/book.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/book.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/book.cpp.i
.PHONY : src/book.cpp.i

src/book.s: src/book.cpp.s
.PHONY : src/book.s

# target to generate assembly for a file
src/book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/book.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/book.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/book.cpp.s
.PHONY : src/book.cpp.s

src/engine.o: src/engine.cpp.o
.PHONY : src/engine.o

# target to build an object file
src/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/engine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/engine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/engine.cpp.o
.PHONY : src/engine.cpp.o

src/engine.i: src/engine.cpp.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/engine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/engine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/engine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/engine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/evaluate.o: src/evaluate.cpp.o
.PHONY : src/evaluate.o

# target to build an object file
src/evaluate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/evaluate.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/evaluate.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/evaluate.cpp.o
.PHONY : src/evaluate.cpp.o

src/evaluate.i: src/evaluate.cpp.i
.PHONY : src/evaluate.i

# target to preprocess a source file
src/evaluate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/evaluate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/evaluate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/evaluate.cpp.i
.PHONY : src/evaluate.cpp.i

src/evaluate.s: src/evaluate.cpp.s
.PHONY : src/evaluate.s

# target to generate assembly for a file
src/evaluate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/evaluate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/evaluate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/evaluate.cpp.s
.PHONY : src/evaluate.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/move.o: src/move.cpp.o
.PHONY : src/move.o

# target to build an object file
src/move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/move.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/move.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/move.cpp.o
.PHONY : src/move.cpp.o

src/move.i: src/move.cpp.i
.PHONY : src/move.i

# target to preprocess a source file
src/move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/move.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/move.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/move.cpp.i
.PHONY : src/move.cpp.i

src/move.s: src/move.cpp.s
.PHONY : src/move.s

# target to generate assembly for a file
src/move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/move.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/move.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/move.cpp.s
.PHONY : src/move.cpp.s

src/movegen.o: src/movegen.cpp.o
.PHONY : src/movegen.o

# target to build an object file
src/movegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/movegen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/movegen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/movegen.cpp.o
.PHONY : src/movegen.cpp.o

src/movegen.i: src/movegen.cpp.i
.PHONY : src/movegen.i

# target to preprocess a source file
src/movegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/movegen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/movegen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/movegen.cpp.i
.PHONY : src/movegen.cpp.i

src/movegen.s: src/movegen.cpp.s
.PHONY : src/movegen.s

# target to generate assembly for a file
src/movegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/movegen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/movegen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/movegen.cpp.s
.PHONY : src/movegen.cpp.s

src/nnue.o: src/nnue.cpp.o
.PHONY : src/nnue.o

# target to build an object file
src/nnue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/nnue.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/nnue.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/nnue.cpp.o
.PHONY : src/nnue.cpp.o

src/nnue.i: src/nnue.cpp.i
.PHONY : src/nnue.i

# target to preprocess a source file
src/nnue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/nnue.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/nnue.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/nnue.cpp.i
.PHONY : src/nnue.cpp.i

src/nnue.s: src/nnue.cpp.s
.PHONY : src/nnue.s

# target to generate assembly for a file
src/nnue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/nnue.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/nnue.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/nnue.cpp.s
.PHONY : src/nnue.cpp.s

src/position.o: src/position.cpp.o
.PHONY : src/position.o

# target to build an object file
src/position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/position.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/position.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/position.cpp.o
.PHONY : src/position.cpp.o

src/position.i: src/position.cpp.i
.PHONY : src/position.i

# target to preprocess a source file
src/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/position.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/position.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/position.cpp.i
.PHONY : src/position.cpp.i

src/position.s: src/position.cpp.s
.PHONY : src/position.s

# target to generate assembly for a file
src/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/position.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/position.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/position.cpp.s
.PHONY : src/position.cpp.s

src/search.o: src/search.cpp.o
.PHONY : src/search.o

# target to build an object file
src/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/search.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/search.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/search.cpp.o
.PHONY : src/search.cpp.o

src/search.i: src/search.cpp.i
.PHONY : src/search.i

# target to preprocess a source file
src/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/search.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/search.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/search.cpp.i
.PHONY : src/search.cpp.i

src/search.s: src/search.cpp.s
.PHONY : src/search.s

# target to generate assembly for a file
src/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/search.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/search.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/search.cpp.s
.PHONY : src/search.cpp.s

src/syzygy.o: src/syzygy.cpp.o
.PHONY : src/syzygy.o

# target to build an object file
src/syzygy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/syzygy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/syzygy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/syzygy.cpp.o
.PHONY : src/syzygy.cpp.o

src/syzygy.i: src/syzygy.cpp.i
.PHONY : src/syzygy.i

# target to preprocess a source file
src/syzygy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/syzygy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/syzygy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/syzygy.cpp.i
.PHONY : src/syzygy.cpp.i

src/syzygy.s: src/syzygy.cpp.s
.PHONY : src/syzygy.s

# target to generate assembly for a file
src/syzygy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/syzygy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/syzygy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/syzygy.cpp.s
.PHONY : src/syzygy.cpp.s

src/tt.o: src/tt.cpp.o
.PHONY : src/tt.o

# target to build an object file
src/tt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/tt.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/tt.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/tt.cpp.o
.PHONY : src/tt.cpp.o

src/tt.i: src/tt.cpp.i
.PHONY : src/tt.i

# target to preprocess a source file
src/tt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/tt.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/tt.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/tt.cpp.i
.PHONY : src/tt.cpp.i

src/tt.s: src/tt.cpp.s
.PHONY : src/tt.s

# target to generate assembly for a file
src/tt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/tt.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/tt.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/tt.cpp.s
.PHONY : src/tt.cpp.s

src/zobrist.o: src/zobrist.cpp.o
.PHONY : src/zobrist.o

# target to build an object file
src/zobrist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/zobrist.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/zobrist.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/zobrist.cpp.o
.PHONY : src/zobrist.cpp.o

src/zobrist.i: src/zobrist.cpp.i
.PHONY : src/zobrist.i

# target to preprocess a source file
src/zobrist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/zobrist.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/zobrist.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/zobrist.cpp.i
.PHONY : src/zobrist.cpp.i

src/zobrist.s: src/zobrist.cpp.s
.PHONY : src/zobrist.s

# target to generate assembly for a file
src/zobrist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_wizard.dir/build.make CMakeFiles/chess_wizard.dir/src/zobrist.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard.dir/build.make CMakeFiles/libchesswizard.dir/src/zobrist.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libchesswizard_shared.dir/build.make CMakeFiles/libchesswizard_shared.dir/src/zobrist.cpp.s
.PHONY : src/zobrist.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chess_wizard"
	@echo "... libchesswizard"
	@echo "... libchesswizard_shared"
	@echo "... src/attack.o"
	@echo "... src/attack.i"
	@echo "... src/attack.s"
	@echo "... src/bitboard.o"
	@echo "... src/bitboard.i"
	@echo "... src/bitboard.s"
	@echo "... src/book.o"
	@echo "... src/book.i"
	@echo "... src/book.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/evaluate.o"
	@echo "... src/evaluate.i"
	@echo "... src/evaluate.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/move.o"
	@echo "... src/move.i"
	@echo "... src/move.s"
	@echo "... src/movegen.o"
	@echo "... src/movegen.i"
	@echo "... src/movegen.s"
	@echo "... src/nnue.o"
	@echo "... src/nnue.i"
	@echo "... src/nnue.s"
	@echo "... src/position.o"
	@echo "... src/position.i"
	@echo "... src/position.s"
	@echo "... src/search.o"
	@echo "... src/search.i"
	@echo "... src/search.s"
	@echo "... src/syzygy.o"
	@echo "... src/syzygy.i"
	@echo "... src/syzygy.s"
	@echo "... src/tt.o"
	@echo "... src/tt.i"
	@echo "... src/tt.s"
	@echo "... src/zobrist.o"
	@echo "... src/zobrist.i"
	@echo "... src/zobrist.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

